permalink: /:year/:month/:title.html
markdown: rdiscount
lsi: false
highlighter: pygments

canonical_url: http://geek.pittcrew.net

exclude: [Gemfile, Gemfile.lock, Rakefile]

analytics:
    tracking_id: UA-36122413-1
