permalink: /:year/:month/:title.html
lsi: false
highlighter: rouge

plugins:
    - jekyll-sitemap

canonical_url: http://geek.pittcrew.net

exclude: [Gemfile, Gemfile.lock, Rakefile]

analytics:
    tracking_id: UA-36122413-1
